import numpy as np
import random
from copy import deepcopy


deck = [    {"value": 0, "suit": "heart"},
            {"value": 1, "suit": "heart"},
            {"value": 2, "suit": "heart"},
            {"value": 3, "suit": "heart"},
            {"value": 4, "suit": "heart"},
            {"value": 5, "suit": "heart"},
            {"value": 6, "suit": "heart"},
            {"value": 7, "suit": "heart"},
            {"value": 8, "suit": "heart"},
            {"value": 9, "suit": "heart"},
            {"value": 10, "suit": "heart"},
            {"value": 11, "suit": "heart"},
            {"value": 12, "suit": "heart"},
            {"value": 0, "suit": "diamond"},
            {"value": 1, "suit": "diamond"},
            {"value": 2, "suit": "diamond"},
            {"value": 3, "suit": "diamond"},
            {"value": 4, "suit": "diamond"},
            {"value": 5, "suit": "diamond"},
            {"value": 6, "suit": "diamond"},
            {"value": 7, "suit": "diamond"},
            {"value": 8, "suit": "diamond"},
            {"value": 9, "suit": "diamond"},
            {"value": 10, "suit": "diamond"},
            {"value": 11, "suit": "diamond"},
            {"value": 12, "suit": "diamond"},
            {"value": 0, "suit": "spade"},
            {"value": 1, "suit": "spade"},
            {"value": 2, "suit": "spade"},
            {"value": 3, "suit": "spade"},
            {"value": 4, "suit": "spade"},
            {"value": 5, "suit": "spade"},
            {"value": 6, "suit": "spade"},
            {"value": 7, "suit": "spade"},
            {"value": 8, "suit": "spade"},
            {"value": 9, "suit": "spade"},
            {"value": 10, "suit": "spade"},
            {"value": 11, "suit": "spade"},
            {"value": 12, "suit": "spade"},
            {"value": 0, "suit": "club"},
            {"value": 1, "suit": "club"},
            {"value": 2, "suit": "club"},
            {"value": 3, "suit": "club"},
            {"value": 4, "suit": "club"},
            {"value": 5, "suit": "club"},
            {"value": 6, "suit": "club"},
            {"value": 7, "suit": "club"},
            {"value": 8, "suit": "club"},
            {"value": 9, "suit": "club"},
            {"value": 10, "suit": "club"},
            {"value": 11, "suit": "club"},
            {"value": 12, "suit": "club"} ]

lookup_table = {
    "2h": {"value": 0, "suit": "heart"},
    "3h": {"value": 1, "suit": "heart"},
    "4h": {"value": 2, "suit": "heart"},
    "5h": {"value": 3, "suit": "heart"},
    "6h": {"value": 4, "suit": "heart"},
    "7h": {"value": 5, "suit": "heart"},
    "8h": {"value": 6, "suit": "heart"},
    "9h": {"value": 7, "suit": "heart"},
    "Th": {"value": 8, "suit": "heart"},
    "Jh": {"value": 9, "suit": "heart"},
    "Qh": {"value": 10, "suit": "heart"},
    "Kh": {"value": 11, "suit": "heart"},
    "Ah": {"value": 12, "suit": "heart"},
    "2d": {"value": 0, "suit": "diamond"},
    "3d": {"value": 1, "suit": "diamond"},
    "4d": {"value": 2, "suit": "diamond"},
    "5d": {"value": 3, "suit": "diamond"},
    "6d": {"value": 4, "suit": "diamond"},
    "7d": {"value": 5, "suit": "diamond"},
    "8d": {"value": 6, "suit": "diamond"},
    "9d": {"value": 7, "suit": "diamond"},
    "Td": {"value": 8, "suit": "diamond"},
    "Jd": {"value": 9, "suit": "diamond"},
    "Qd": {"value": 10, "suit": "diamond"},
    "Kd": {"value": 11, "suit": "diamond"},
    "Ad": {"value": 12, "suit": "diamond"},
    "2s": {"value": 0, "suit": "spade"},
    "3s": {"value": 1, "suit": "spade"},
    "4s": {"value": 2, "suit": "spade"},
    "5s": {"value": 3, "suit": "spade"},
    "6s": {"value": 4, "suit": "spade"},
    "7s": {"value": 5, "suit": "spade"},
    "8s": {"value": 6, "suit": "spade"},
    "9s": {"value": 7, "suit": "spade"},
    "Ts": {"value": 8, "suit": "spade"},
    "Js": {"value": 9, "suit": "spade"},
    "Qs": {"value": 10, "suit": "spade"},
    "Ks": {"value": 11, "suit": "spade"},
    "As": {"value": 12, "suit": "spade"},
    "2c": {"value": 0, "suit": "club"},
    "3c": {"value": 1, "suit": "club"},
    "4c": {"value": 2, "suit": "club"},
    "5c": {"value": 3, "suit": "club"},
    "6c": {"value": 4, "suit": "club"},
    "7c": {"value": 5, "suit": "club"},
    "8c": {"value": 6, "suit": "club"},
    "9c": {"value": 7, "suit": "club"},
    "Tc": {"value": 8, "suit": "club"},
    "Jc": {"value": 9, "suit": "club"},
    "Qc": {"value": 10, "suit": "club"},
    "Kc": {"value": 11, "suit": "club"},
    "Ac": {"value": 12, "suit": "club"} 
}



training = ["Full Tilt Poker Game #1: Table Cleverpiggy - FL Hold'em - 2/4 - 01:11:41 GMT - 2018/12/16", 
'Seat 1: anonymous (1000)', 'Seat 2: Cleverpiggy (1000)', 'anonymous posts the small blind of 1', 
'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [9d 6h]', 'anonymous raises to 4', 
'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [7c 3s]', 'anonymous wins the pot ($4)', 
"Full Tilt Poker Game #2: Table Cleverpiggy - FL Hold'em - 2/4 - 01:11:44 GMT - 2018/12/16", 
'Seat 1: anonymous (1002)', 'Seat 2: Cleverpiggy (998)', 'Cleverpiggy posts the small blind of 1', 
'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [7s 8s]', 'Cleverpiggy raises to 4', 
'anonymous calls 2', '*** FLOP *** [3c Qs Ac]', 'anonymous bets 2', 'Cleverpiggy calls 2', '*** TURN *** [5h]', 
'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [4s]', 'anonymous checks', 'Cleverpiggy bets 4', 
'anonymous raises to 8', 'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [3s Jd]', 'anonymous wins the pot ($28)', 
"Full Tilt Poker Game #3: Table Cleverpiggy - FL Hold'em - 2/4 - 01:11:55 GMT - 2018/12/16", 'Seat 1: anonymous (1016)', 
'Seat 2: Cleverpiggy (984)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', 
'*** HOLE CARDS ***', 'Dealt to anonymous [Td 4s]', 'anonymous calls 1', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 
'Cleverpiggy calls 2', '*** FLOP *** [Jc Ad 8s]', 'Cleverpiggy checks', 'anonymous checks', '*** TURN *** [5h]', 
'Cleverpiggy checks', 'anonymous checks', '*** RIVER *** [5d]', 'Cleverpiggy checks', 'anonymous checks', 
'*** Show Down ***', 'Cleverpiggy shows [3c Kh]', 'Cleverpiggy wins the pot ($12)', 
"Full Tilt Poker Game #4: Table Cleverpiggy - FL Hold'em - 2/4 - 01:12:06 GMT - 2018/12/16", 'Seat 1: anonymous (1010)', 
'Seat 2: Cleverpiggy (990)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 
'Dealt to anonymous [9c Td]', 'Cleverpiggy raises to 4', 'anonymous calls 2', '*** FLOP *** [8s 6h Kh]', 'anonymous checks', 
'Cleverpiggy bets 2', 'anonymous calls 2', '*** TURN *** [7d]', 'anonymous checks', 'Cleverpiggy bets 4', 'anonymous calls 4', 
'*** RIVER *** [Ad]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [5d 7c]', 
'anonymous wins the pot ($28)', "Full Tilt Poker Game #5: Table Cleverpiggy - FL Hold'em - 2/4 - 01:12:16 GMT - 2018/12/16", 'Seat 1: anonymous (1024)', 'Seat 2: Cleverpiggy (976)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [8h Ad]', 'anonymous raises to 4', 'Cleverpiggy raises to 6', 'anonymous calls 2', '*** FLOP *** [5d Kh 4s]', 'Cleverpiggy bets 2', 'anonymous calls 2', '*** TURN *** [9h]', 'Cleverpiggy checks', 'anonymous checks', '*** RIVER *** [Jh]', 'Cleverpiggy checks', 'anonymous bets 4', 'Cleverpiggy raises to 8', 'anonymous calls 4', '*** Show Down ***', 'Cleverpiggy shows [Kd Ks]', 'Cleverpiggy wins the pot ($32)', "Full Tilt Poker Game #6: Table Cleverpiggy - FL Hold'em - 2/4 - 01:12:27 GMT - 2018/12/16", 'Seat 1: anonymous (1008)', 'Seat 2: Cleverpiggy (992)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [9c Qs]', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** FLOP *** [5d 3h 2s]', 'anonymous checks', 'Cleverpiggy checks', '*** TURN *** [2c]', 'anonymous checks', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy raises to 12', 'anonymous calls 4', '*** RIVER *** [7h]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [Qd 2d]', 'Cleverpiggy wins the pot ($44)', "Full Tilt Poker Game #7: Table Cleverpiggy - FL Hold'em - 2/4 - 01:12:39 GMT - 2018/12/16", 'Seat 1: anonymous (986)', 'Seat 2: Cleverpiggy (1014)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [4h 3d]', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [Ks 9h Js]', 'Cleverpiggy checks', 'anonymous checks', '*** TURN *** [Td]', 'Cleverpiggy checks', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [2d]', 'Cleverpiggy checks', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [Jc 3c]', 'Cleverpiggy wins the pot ($24)', "Full Tilt Poker Game #8: Table Cleverpiggy - FL Hold'em - 2/4 - 01:12:51 GMT - 2018/12/16", 'Seat 1: anonymous (974)', 'Seat 2: Cleverpiggy (1026)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [2s 2c]', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** FLOP *** [2d 6d 9s]', 'anonymous checks', 'Cleverpiggy checks', '*** TURN *** [3h]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [Qc]', 'anonymous checks', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy raises to 12', 'anonymous raises to 16', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [Qd Ah]', 'anonymous wins the pot ($52)', "Full Tilt Poker Game #9: Table Cleverpiggy - FL Hold'em - 2/4 - 01:13:04 GMT - 2018/12/16", 'Seat 1: anonymous (1000)', 'Seat 2: Cleverpiggy (1000)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [4s 9s]', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [3d 6h Tc]', 'Cleverpiggy checks', 'anonymous bets 2', 'Cleverpiggy calls 2', '*** TURN *** [3c]', 'Cleverpiggy checks', 'anonymous checks', '*** RIVER *** [9h]', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** Show Down ***', 'Cleverpiggy shows [6s 7h]', 'anonymous wins the pot ($20)', "Full Tilt Poker Game #10: Table Cleverpiggy - FL Hold'em - 2/4 - 01:13:14 GMT - 2018/12/16", 'Seat 1: anonymous (1010)', 'Seat 2: Cleverpiggy (990)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Td 8h]', 'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [2d Ts]', 'anonymous wins the pot ($2)', "Full Tilt Poker Game #11: Table Cleverpiggy - FL Hold'em - 2/4 - 01:13:18 GMT - 2018/12/16", 'Seat 1: anonymous (1011)', 'Seat 2: Cleverpiggy (989)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Kh 7c]', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [9s 3d Jc]', 'Cleverpiggy checks', 'anonymous bets 2', 'Cleverpiggy raises to 4', 'anonymous calls 2', '*** TURN *** [3c]', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** RIVER *** [2c]', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [Qc 3s]', 'Cleverpiggy wins the pot ($40)', "Full Tilt Poker Game #12: Table Cleverpiggy - FL Hold'em - 2/4 - 01:13:30 GMT - 2018/12/16", 'Seat 1: anonymous (991)', 'Seat 2: Cleverpiggy (1009)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [5h 9d]', 'Cleverpiggy raises to 4', 'anonymous calls 2', '*** FLOP *** [3h 2s 5d]', 'anonymous checks', 'Cleverpiggy checks', '*** TURN *** [9c]', 'anonymous checks', 'Cleverpiggy checks', '*** RIVER *** [Ah]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [Qh Ts]', 'anonymous wins the pot ($16)', "Full Tilt Poker Game #13: Table Cleverpiggy - FL Hold'em - 2/4 - 01:13:39 GMT - 2018/12/16", 'Seat 1: anonymous (999)', 'Seat 2: Cleverpiggy (1001)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [As 5h]', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [6c 7d 9d]', 'Cleverpiggy checks', 'anonymous checks', '*** TURN *** [6d]', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** RIVER *** [Th]', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [5s Qh]', 'anonymous wins the pot ($24)', "Full Tilt Poker Game #14: Table Cleverpiggy - FL Hold'em - 2/4 - 01:13:50 GMT - 2018/12/16", 'Seat 1: anonymous (1011)', 'Seat 2: Cleverpiggy (989)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [5d Kh]', 'Cleverpiggy calls 1', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [6c 6s 8s]', 'anonymous checks', 'Cleverpiggy checks', '*** TURN *** [Tc]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [Qs]', 'anonymous checks', 'Cleverpiggy checks', '*** Show Down ***', 'Cleverpiggy shows [Kc 8d]', 'Cleverpiggy wins the pot ($16)', "Full Tilt Poker Game #15: Table Cleverpiggy - FL Hold'em - 2/4 - 01:14:01 GMT - 2018/12/16", 'Seat 1: anonymous (1003)', 'Seat 2: Cleverpiggy (997)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [4h 9d]', 'anonymous calls 1', 'Cleverpiggy checks', '*** FLOP *** [Jc Jh 3h]', 'Cleverpiggy checks', 'anonymous checks', '*** TURN *** [Th]', 'Cleverpiggy checks', 'anonymous bets 4', 'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [Qs 4c]', 'anonymous wins the pot ($4)', "Full Tilt Poker Game #16: Table Cleverpiggy - FL Hold'em - 2/4 - 01:14:10 GMT - 2018/12/16", 'Seat 1: anonymous (1005)', 'Seat 2: Cleverpiggy (995)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [4c Qh]', 'Cleverpiggy raises to 4', 'anonymous calls 2', '*** FLOP *** [4d 8h Qd]', 'anonymous bets 2', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** TURN *** [5s]', 'anonymous checks', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** RIVER *** [7d]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [Th 8d]', 'anonymous wins the pot ($36)', "Full Tilt Poker Game #17: Table Cleverpiggy - FL Hold'em - 2/4 - 01:14:25 GMT - 2018/12/16", 'Seat 1: anonymous (1023)', 'Seat 2: Cleverpiggy (977)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [4d 2c]', 'anonymous raises to 4', 'Cleverpiggy raises to 6', 'anonymous raises to 8', 'Cleverpiggy calls 2', '*** FLOP *** [Kh 9s 7d]', 'Cleverpiggy checks', 'anonymous bets 2', 'Cleverpiggy calls 2', '*** TURN *** [5s]', 'Cleverpiggy checks', 'anonymous checks', '*** RIVER *** [Ts]', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy raises to 12', 'anonymous calls 4', '*** Show Down ***', 'Cleverpiggy shows [6h Ac]', 'Cleverpiggy wins the pot ($44)', "Full Tilt Poker Game #18: Table Cleverpiggy - FL Hold'em - 2/4 - 01:14:38 GMT - 2018/12/16", 'Seat 1: anonymous (1001)', 'Seat 2: Cleverpiggy (999)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Qd Kd]', 'Cleverpiggy raises to 4', 'anonymous calls 2', '*** FLOP *** [Ah 9s Th]', 'anonymous bets 2', 'Cleverpiggy calls 2', '*** TURN *** [2s]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [Ad]', 'anonymous checks', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [4h Ts]', 'Cleverpiggy wins the pot ($36)', "Full Tilt Poker Game #19: Table Cleverpiggy - FL Hold'em - 2/4 - 01:14:49 GMT - 2018/12/16", 'Seat 1: anonymous (983)', 'Seat 2: Cleverpiggy (1017)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Qd Td]', 'anonymous raises to 4', 'Cleverpiggy raises to 6', 'anonymous raises to 8', 'Cleverpiggy calls 2', '*** FLOP *** [3s 7h 5s]', 'Cleverpiggy bets 2', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** TURN *** [3c]', 'Cleverpiggy checks', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [2s]', 'Cleverpiggy checks', 'anonymous checks', '*** Show Down ***', 'Cleverpiggy shows [Kh Th]', 'Cleverpiggy wins the pot ($32)', "Full Tilt Poker Game #20: Table Cleverpiggy - FL Hold'em - 2/4 - 01:15:02 GMT - 2018/12/16", 'Seat 1: anonymous (967)', 'Seat 2: Cleverpiggy (1033)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [4h Jd]', 'Cleverpiggy raises to 4', 'anonymous calls 2', '*** FLOP *** [Ks 5c Ac]', 'anonymous bets 2', 'Cleverpiggy calls 2', '*** TURN *** [Qs]', 'anonymous checks', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [8c 9d]', 'anonymous wins the pot ($20)', "Full Tilt Poker Game #21: Table Cleverpiggy - FL Hold'em - 2/4 - 01:15:11 GMT - 2018/12/16", 'Seat 1: anonymous (977)', 'Seat 2: Cleverpiggy (1023)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Ah 9d]', 'anonymous raises to 4', 'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [3d 7c]', 'anonymous wins the pot ($4)', "Full Tilt Poker Game #22: Table Cleverpiggy - FL Hold'em - 2/4 - 01:15:14 GMT - 2018/12/16", 'Seat 1: anonymous (979)', 'Seat 2: Cleverpiggy (1021)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Ad Tc]', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** FLOP *** [4s Jd 5c]', 'anonymous bets 2', 'Cleverpiggy calls 2', '*** TURN *** [Ks]', 'anonymous bets 4', 'Cleverpiggy raises to 8', 'anonymous calls 4', '*** RIVER *** [2h]', 'anonymous checks', 'Cleverpiggy bets 4']
