import numpy as np
import random
from copy import deepcopy


deck = [    {"value": 0, "suit": "heart"},
            {"value": 1, "suit": "heart"},
            {"value": 2, "suit": "heart"},
            {"value": 3, "suit": "heart"},
            {"value": 4, "suit": "heart"},
            {"value": 5, "suit": "heart"},
            {"value": 6, "suit": "heart"},
            {"value": 7, "suit": "heart"},
            {"value": 8, "suit": "heart"},
            {"value": 9, "suit": "heart"},
            {"value": 10, "suit": "heart"},
            {"value": 11, "suit": "heart"},
            {"value": 12, "suit": "heart"},
            {"value": 0, "suit": "diamond"},
            {"value": 1, "suit": "diamond"},
            {"value": 2, "suit": "diamond"},
            {"value": 3, "suit": "diamond"},
            {"value": 4, "suit": "diamond"},
            {"value": 5, "suit": "diamond"},
            {"value": 6, "suit": "diamond"},
            {"value": 7, "suit": "diamond"},
            {"value": 8, "suit": "diamond"},
            {"value": 9, "suit": "diamond"},
            {"value": 10, "suit": "diamond"},
            {"value": 11, "suit": "diamond"},
            {"value": 12, "suit": "diamond"},
            {"value": 0, "suit": "spade"},
            {"value": 1, "suit": "spade"},
            {"value": 2, "suit": "spade"},
            {"value": 3, "suit": "spade"},
            {"value": 4, "suit": "spade"},
            {"value": 5, "suit": "spade"},
            {"value": 6, "suit": "spade"},
            {"value": 7, "suit": "spade"},
            {"value": 8, "suit": "spade"},
            {"value": 9, "suit": "spade"},
            {"value": 10, "suit": "spade"},
            {"value": 11, "suit": "spade"},
            {"value": 12, "suit": "spade"},
            {"value": 0, "suit": "club"},
            {"value": 1, "suit": "club"},
            {"value": 2, "suit": "club"},
            {"value": 3, "suit": "club"},
            {"value": 4, "suit": "club"},
            {"value": 5, "suit": "club"},
            {"value": 6, "suit": "club"},
            {"value": 7, "suit": "club"},
            {"value": 8, "suit": "club"},
            {"value": 9, "suit": "club"},
            {"value": 10, "suit": "club"},
            {"value": 11, "suit": "club"},
            {"value": 12, "suit": "club"} ]

lookup_table = {
    "2h": {"value": 0, "suit": "heart"},
    "3h": {"value": 1, "suit": "heart"},
    "4h": {"value": 2, "suit": "heart"},
    "5h": {"value": 3, "suit": "heart"},
    "6h": {"value": 4, "suit": "heart"},
    "7h": {"value": 5, "suit": "heart"},
    "8h": {"value": 6, "suit": "heart"},
    "9h": {"value": 7, "suit": "heart"},
    "Th": {"value": 8, "suit": "heart"},
    "Jh": {"value": 9, "suit": "heart"},
    "Qh": {"value": 10, "suit": "heart"},
    "Kh": {"value": 11, "suit": "heart"},
    "Ah": {"value": 12, "suit": "heart"},
    "2d": {"value": 0, "suit": "diamond"},
    "3d": {"value": 1, "suit": "diamond"},
    "4d": {"value": 2, "suit": "diamond"},
    "5d": {"value": 3, "suit": "diamond"},
    "6d": {"value": 4, "suit": "diamond"},
    "7d": {"value": 5, "suit": "diamond"},
    "8d": {"value": 6, "suit": "diamond"},
    "9d": {"value": 7, "suit": "diamond"},
    "Td": {"value": 8, "suit": "diamond"},
    "Jd": {"value": 9, "suit": "diamond"},
    "Qd": {"value": 10, "suit": "diamond"},
    "Kd": {"value": 11, "suit": "diamond"},
    "Ad": {"value": 12, "suit": "diamond"},
    "2s": {"value": 0, "suit": "spade"},
    "3s": {"value": 1, "suit": "spade"},
    "4s": {"value": 2, "suit": "spade"},
    "5s": {"value": 3, "suit": "spade"},
    "6s": {"value": 4, "suit": "spade"},
    "7s": {"value": 5, "suit": "spade"},
    "8s": {"value": 6, "suit": "spade"},
    "9s": {"value": 7, "suit": "spade"},
    "Ts": {"value": 8, "suit": "spade"},
    "Js": {"value": 9, "suit": "spade"},
    "Qs": {"value": 10, "suit": "spade"},
    "Ks": {"value": 11, "suit": "spade"},
    "As": {"value": 12, "suit": "spade"},
    "2c": {"value": 0, "suit": "club"},
    "3c": {"value": 1, "suit": "club"},
    "4c": {"value": 2, "suit": "club"},
    "5c": {"value": 3, "suit": "club"},
    "6c": {"value": 4, "suit": "club"},
    "7c": {"value": 5, "suit": "club"},
    "8c": {"value": 6, "suit": "club"},
    "9c": {"value": 7, "suit": "club"},
    "Tc": {"value": 8, "suit": "club"},
    "Jc": {"value": 9, "suit": "club"},
    "Qc": {"value": 10, "suit": "club"},
    "Kc": {"value": 11, "suit": "club"},
    "Ac": {"value": 12, "suit": "club"} 
}


training = ["Full Tilt Poker Game #1: Table Cleverpiggy - FL Hold'em - 2/4 - 02:47:10 GMT - 2018/12/17", 'Seat 1: anonymous (1000)', 'Seat 2: Cleverpiggy (1000)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Qh 6d]', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [7s 7c Jc]', 'Cleverpiggy checks', 'anonymous bets 2', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** TURN *** [7h]', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy calls 4', '*** RIVER *** [Js]', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** Show Down ***', 'Cleverpiggy shows [Jh 8d]', 'Cleverpiggy wins the pot ($44)', "Full Tilt Poker Game #2: Table Cleverpiggy - FL Hold'em - 2/4 - 02:47:37 GMT - 2018/12/17", 'Seat 1: anonymous (978)', 'Seat 2: Cleverpiggy (1022)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [2d Kh]', 'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [2h 5d]', 'anonymous wins the pot ($2)', "Full Tilt Poker Game #3: Table Cleverpiggy - FL Hold'em - 2/4 - 02:47:43 GMT - 2018/12/17", 'Seat 1: anonymous (979)', 'Seat 2: Cleverpiggy (1021)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Ad Kh]', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [2d 7s 7h]', 'Cleverpiggy checks', 'anonymous checks', '*** TURN *** [6c]', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** RIVER *** [5d]', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** Show Down ***', 'Cleverpiggy shows [Ts 6h]', 'Cleverpiggy wins the pot ($24)', "Full Tilt Poker Game #4: Table Cleverpiggy - FL Hold'em - 2/4 - 02:48:15 GMT - 2018/12/17", 'Seat 1: anonymous (967)', 'Seat 2: Cleverpiggy (1033)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [5h 5s]', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** FLOP *** [Kh As Js]', 'anonymous bets 2', 'Cleverpiggy calls 2', '*** TURN *** [8c]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [7d]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [2s Ks]', 'Cleverpiggy wins the pot ($32)', "Full Tilt Poker Game #5: Table Cleverpiggy - FL Hold'em - 2/4 - 02:48:42 GMT - 2018/12/17", 'Seat 1: anonymous (951)', 'Seat 2: Cleverpiggy (1049)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [3d 5h]', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [5d 2h 7s]', 'Cleverpiggy bets 2', 'anonymous calls 2', '*** TURN *** [Ts]', 'Cleverpiggy bets 4', 'anonymous raises to 8', 'Cleverpiggy calls 4', '*** RIVER *** [Qd]', 'Cleverpiggy checks', 'anonymous checks', '*** Show Down ***', 'Cleverpiggy shows [4d 5s]', 'anonymous ties for the pot ($14)', 'Cleverpiggy ties for the pot ($14)', "Full Tilt Poker Game #6: Table Cleverpiggy - FL Hold'em - 2/4 - 02:49:11 GMT - 2018/12/17", 'Seat 1: anonymous (951)', 'Seat 2: Cleverpiggy (1049)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [9s As]', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy raises to 8', 'anonymous calls 2', '*** FLOP *** [5c Ah 7s]', 'anonymous bets 2', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** TURN *** [2d]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [Qh]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** Show Down ***', 'Cleverpiggy shows [7c Kd]', 'anonymous wins the pot ($44)', "Full Tilt Poker Game #7: Table Cleverpiggy - FL Hold'em - 2/4 - 02:50:06 GMT - 2018/12/17", 'Seat 1: anonymous (973)', 'Seat 2: Cleverpiggy (1027)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [8c Qc]', 'anonymous raises to 4', 'Cleverpiggy calls 2', '*** FLOP *** [3h 7d 3s]', 'Cleverpiggy checks', 'anonymous checks', '*** TURN *** [5s]', 'Cleverpiggy checks', 'anonymous checks', '*** RIVER *** [Jc]', 'Cleverpiggy checks', 'anonymous checks', '*** Show Down ***', 'Cleverpiggy shows [2c 9h]', 'anonymous wins the pot ($8)', "Full Tilt Poker Game #8: Table Cleverpiggy - FL Hold'em - 2/4 - 02:50:37 GMT - 2018/12/17", 'Seat 1: anonymous (977)', 'Seat 2: Cleverpiggy (1023)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [As Qs]', 'Cleverpiggy folds', '*** Show Down ***', 'Cleverpiggy shows [4h 3c]', 'anonymous wins the pot ($2)', "Full Tilt Poker Game #9: Table Cleverpiggy - FL Hold'em - 2/4 - 02:50:44 GMT - 2018/12/17", 'Seat 1: anonymous (978)', 'Seat 2: Cleverpiggy (1022)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Kh Qs]', 'anonymous calls 1', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** FLOP *** [Ac 5s Qc]', 'Cleverpiggy bets 2', 'anonymous calls 2', '*** TURN *** [6d]', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** RIVER *** [8c]', 'Cleverpiggy bets 4', 'anonymous calls 4', '*** Show Down ***', 'Cleverpiggy shows [3h As]', 'Cleverpiggy wins the pot ($32)', "Full Tilt Poker Game #10: Table Cleverpiggy - FL Hold'em - 2/4 - 02:51:23 GMT - 2018/12/17", 'Seat 1: anonymous (962)', 'Seat 2: Cleverpiggy (1038)', 'Cleverpiggy posts the small blind of 1', 'anonymous posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [Qd 7d]', 'Cleverpiggy raises to 4', 'anonymous calls 2', '*** FLOP *** [2h 6c 6s]', 'anonymous bets 2', 'Cleverpiggy raises to 4', 'anonymous raises to 6', 'Cleverpiggy calls 2', '*** TURN *** [3c]', 'anonymous bets 4', 'Cleverpiggy calls 4', '*** RIVER *** [Jc]', 'anonymous checks', 'Cleverpiggy checks', '*** Show Down ***', 'Cleverpiggy shows [Td 2d]', 'Cleverpiggy wins the pot ($28)', "Full Tilt Poker Game #11: Table Cleverpiggy - FL Hold'em - 2/4 - 02:52:01 GMT - 2018/12/17", 'Seat 1: anonymous (948)', 'Seat 2: Cleverpiggy (1052)', 'anonymous posts the small blind of 1', 'Cleverpiggy posts the big blind of 2', '*** HOLE CARDS ***', 'Dealt to anonymous [As 2c]', 'anonymous calls 1', 'Cleverpiggy raises to 4', 'anonymous calls 2']